version: "3.8"

services:
  ##### MongoDB #####
  mongodb:
    container_name: mongodb
    image: mongo:5.0.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=eventsshop
    volumes:
      - ./demo_data/recipes.json:/data/listings.json
      - ./demo_data/populate.sh:/docker-entrypoint-initdb.d/populate.sh
      - ./tmp/mongo/data/db:/data/db
    ports:
      - "27017:27017"
networks:
  default:
    name: checkoutevents
    driver: bridge
